apiVersion: apps/v1
kind: Deployment
metadata:
  name: coubee-be-order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coubee-be-order
  template:
    metadata:
      labels:
        app: coubee-be-order
    spec:
      containers:
        - name: coubee-be-order
          image: mingyoolee/coubee-be-order:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: stg
          ports:
            - containerPort: 8083
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - mountPath: /etc/config
              name: be-order-config-volume
            - mountPath: /etc/secret
              name: be-order-secret-volume
      volumes:
        - name: be-order-config-volume
          configMap:
            name: be-order-config
            items:
              - key: application-stg.yml
                path: application-stg.yml
        - name: be-order-secret-volume
          secret:
            secretName: be-order-secret
            items:
              - key: application-secret.yml
                path: application-secret.yml