apiVersion: apps/v1
kind: Deployment
metadata:
  name: coubee-be-order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coubee-be-order
  template:
    metadata:
      labels:
        app: coubee-be-order
    spec:
      containers:
        - name: coubee-be-order
          image: mingyoolee/coubee-be-order:0.0.3
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: stg
            - name: SPRING_CONFIG_LOCATION
              value: file:/etc/config/application-stg.yml,file:/etc/secret/application-secret.yml
            # Kubernetes API 비활성화 추가
            - name: SPRING_CLOUD_KUBERNETES_ENABLED
              value: "false"
            - name: SPRING_CLOUD_KUBERNETES_DISCOVERY_ENABLED
              value: "false"
            - name: SPRING_CLOUD_KUBERNETES_CONFIG_ENABLED
              value: "false"
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/config
              name: be-order-config-volume
            - mountPath: /etc/secret
              name: be-order-secret-volume
          livenessProbe:
            httpGet:
              # [수정] Actuator 상태 그룹 경로 대신 실제 컨트롤러 경로로 수정합니다.
              path: /api/health/live
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 5
          readinessProbe:
            httpGet:
              # [수정] Actuator 상태 그룹 경로 대신 실제 컨트롤러 경로로 수정합니다.
              path: /api/health/ready
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 5
      volumes:
        - name: be-order-config-volume
          configMap:
            name: be-order-config
            items:
              - key: application-stg.yml
                path: application-stg.yml
        - name: be-order-secret-volume
          secret:
            secretName: be-order-secret
            items:
              - key: application-secret.yml
                path: application-secret.yml