apiVersion: v1
kind: ConfigMap
metadata:
  name: be-order-config
data:
  application-stg.yml: |
    server:
      port: 8080
    
    spring:
      # # 1. Flyway 에러 해결: 현재 DB 상태가 V4임을 명시
      flyway:
        repair-on-migrate: true
      #   baseline-on-migrate: true
      #   baseline-version: 4

      datasource:
        # 2. 스키마 경로 문제 해결: 모든 DB 연결이 coubee_order 스키마를 보도록 강제
        url: jdbc:postgresql://52.78.117.85:5432/coubee_order?currentSchema=coubee_order
        driver-class-name: org.postgresql.Driver
        hikari:
          # Production-ready connection pool settings
          maximum-pool-size: 50
          minimum-idle: 10
          idle-timeout: 300000
          connection-timeout: 20000
          max-lifetime: 1800000
          connection-test-query: SELECT 1
          validation-timeout: 5000
          leak-detection-threshold: 60000
      
      jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          ddl-auto: validate
        show-sql: true
        open-in-view: false
        properties:
          hibernate:
            default_schema: coubee_order
            # N+1 문제를 해결하고 성능을 최적화하기 위해 배치 페치 크기를 설정합니다.
            # (Set the batch fetch size to resolve N+1 problems and optimize performance.)
            default_batch_fetch_size: 100
      
      kafka:
        bootstrap-servers: coubee-external-kafka-service:9092
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
          properties:
            spring.json.add.type.headers: false
    
    portone:
      api:
        url: https://api.portone.io
        version: v2