# 개발 환경(dev profile) 전용 설정
spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    config:
      # Spring Cloud Config 클라이언트 기능을 비활성화합니다.
      enabled: false
  
  # H2 메모리 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  
  # Flyway 비활성화
  flyway:
    enabled: false
    
  kafka:
    bootstrap-servers: localhost:29092

server:
  port: 8083

# Eureka 설정
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# PortOne API 설정
portone:
  api:
    url: https://api.portone.io
    secret: test_secret
  v2:
    store-id: ${PORTONE_STORE_ID:store-a9463375-7b07-40fc-8c4f-e0bd4fb0c2b7}
    api-secret: ${PORTONE_API_SECRET:zncFiBtA0lilnsWsTaBUgepbSSp7YYbXFOvI62d9jJ3RfEpM9Tjqr3ikg1BRyUM6DFmXrAwZ43ryLamW}
    channels:
      # 각 결제 수단별 채널 키 (환경 변수로 주입 가능) - 모든 키를 소문자로 통일
      card: ${PORTONE_CHANNEL_KEY_TOSSPAYMENTS:channel-key-a448c12c-9f97-4eeb-9506-97279641dbf9}
      kakaopay: ${PORTONE_CHANNEL_KEY_KAKAOPAY:channel-key-e19a56d4-1583-46c6-a37f-19944df75a35}
      tosspay: ${PORTONE_CHANNEL_KEY_TOSSPAY:channel-key-aaea2e9f-efec-4565-9619-0173d51cc4a6}
      payco: ${PORTONE_CHANNEL_KEY_PAYCO:channel-key-401582f6-2c72-479e-a04b-2a68f1d09afe}
# Logging 설정
logging:
  level:
    com.coubee: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springdoc: DEBUG
    org.springframework.boot: DEBUG

# H2 콘솔 활성화
spring.h2.console:
  enabled: true
  path: /h2-console

# Swagger 설정
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true 